# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.10.1'
  displayName: 'Install Node.js'

- script: |
    cd vue-spider
    npm install
    npm run build
    cd ../egg
    npm install --production
    cd ..
    tar -zcvf egg.tar.gz egg
    tar -zcvf spider.tar.gz vue-spider/spider
    mkdir cpl
    cp egg.tar.gz cpl
    cp spider.tar.gz cpl
  displayName: 'npm install and build'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: '149.248.5.21'
    sourceFolder: 'cpl'
    contents: '**'
    targetFolder: '/home/wwwroot/jizhi.jinjun.wiki/cpl'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: '149.248.5.21'
    runOptions: 'inline'
    inline: |
      cd /home/wwwroot/jizhi.jinjun.wiki/cpl
      tar -zxvf spider.tar.gz
      tar -zxvf egg.tar.gz
      cp -r vue-spider/spider ../
      cd egg
      npm stop 
      npm start
    readyTimeout: '20000'